# Generated by Django 3.1.7 on 2021-06-01 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_post_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=225, verbose_name='Название')),
                ('image', models.ImageField(db_index=True, upload_to='', verbose_name='Картинка')),
                ('public', models.BooleanField(default=False, verbose_name='Публиковать')),
                ('slug', models.SlugField(unique=True, verbose_name='Ссылка')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('view', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('video', models.FileField(null=True, upload_to='', verbose_name='Траилер')),
                ('money', models.IntegerField(verbose_name='Бюджет')),
                ('director', models.CharField(max_length=225, verbose_name='Режисёр')),
                ('writer', models.CharField(max_length=225, verbose_name='Сценарист')),
                ('about', models.TextField(verbose_name='О фильме')),
                ('country', models.CharField(max_length=225, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
    ]
