# Generated by Django 4.0.2 on 2022-07-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_alter_collection_id_alter_comment_id_alter_movie_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.FileField(null=True, upload_to='', verbose_name='Трейлер'),
        ),
    ]
